Adds post-commit and updates pre-commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,5 @@
 #!/bin/sh
-echo "\033[1;34mRunning pre-commit hook\033[0m"
+printf "\033[1;34mRunning pre-commit hook\033[0m\n"
 
 FILES=$(git diff --cached --name-only --diff-filter=ACM | \
 	grep -E "\.rs$|\.[tj]s$")
@@ -10,25 +10,25 @@ if [ -z $FILES ]; then exit 0; fi
 # Check that rustup is installed
 rustup --version > /dev/null 2>&1
 if [ "$?" -ne 0 ]; then
-	echo  "\033[1;31mCan't find rustup, please install it/add it to path\033[0m"
+	printf "\033[1;31mCan't find rustup, please install it/add it to path\033[0m\n"
 	exit 1
 fi
 
 # Check that nightly is installed (for rustfmt)
 if [ -z "$(rustup toolchain list | grep nightly)" ]; then
-	echo  "rustup nightly not found, attempting to install"
-	echo  "Running \"\033[0;34mrustup toolchain install nightly\033[0m\""
-    rustup toolchain install nightly
-    
+	printf "rustup nightly not found, attempting to install\n"
+	printf "Running \"\033[0;34mrustup toolchain install nightly\033[0m\"\n"
+	rustup toolchain install nightly
+	
 	# If it couldn't install, fail
-    if [ "$?" -ne 9 ]; then exit 1; fi
+	if [ "$?" -ne 9 ]; then exit 1; fi
 fi
 
 # Check that rustfmt is installed. If not, try to install
 rustfmt --version > /dev/null 2>&1
 if [ "$?" -ne 0 ]; then
-	echo  "rustfmt not found, attempting to install"
-	echo  "Running \"\033[0;34mrustup component add rustfmt\033[0m\""
+	printf "rustfmt not found, attempting to install\n"
+	printf "Running \"\033[0;34mrustup component add rustfmt\033[0m\"\n"
 	rustup component add rustfmt --toolchain nightly
 
 	if [ "$?" -ne 0 ]; then exit 1; fi
@@ -37,8 +37,8 @@ fi
 # Check that clippy is installed. If not, try to install
 clippy-driver --version > /dev/null 2>&1
 if [ "$?" -ne 0 ]; then
-	echo  "clippy not found, attempting to install"
-	echo  "Running \"\033[0;34mrustup component add clippy\033[0m\""
+	printf "clippy not found, attempting to install\n"
+	printf "Running \"\033[0;34mrustup component add clippy\033[0m\"\n"
 	rustup component add clippy 
 
 	if [ "$?" -ne 0 ]; then exit 1; fi
@@ -47,14 +47,14 @@ fi
 # Check that npm is installed
 npm --version > /dev/null 2>&1
 if [ "$?" -ne 0 ]; then
-	echo  "\033[1;31mCan't find nodejs, please install it/add it to path\033[0m"
+	printf "\033[1;31mCan't find nodejs, please install it/add it to path\033[0m\n"
 	exit 1
 fi
 
 # Check that eslint is installed. If not, try to install
 if [ ! -f ./node_modules/.bin/eslint ]; then 
-	echo  "eslint not found, attempting to install"
-	echo  "Running \"\033[0;34mrnpm install\033[0m\""
+	printf "eslint not found, attempting to install\n"
+	printf "Running \"\033[0;34mrnpm install\033[0m\"\n"
 	npm install
 
 	if [ "$?" -ne 0 ]; then exit 1; fi
@@ -68,14 +68,14 @@ ESLINT="./node_modules/.bin/eslint"
 # just disallow it for the specific line and write a comment saying that
 # it triggers a false postiive
 
-echo  "\033[1;34mRunning clippy\033[0m"
+printf "\033[1;34mRunning clippy\033[0m\n"
 cargo clippy -- -A \
 	clippy::blocks-in-if-conditions \
 	-D warnings
 
 if [ "$?" -ne 0 ]; then exit 1; fi
 
-echo  "\033[1;34mRunning rustfmt\033[0m"
+printf "\033[1;34mRunning rustfmt\033[0m\n"
 FILES_FORMATTED=""
 RUSTFMT_OPTIONS="--unstable-features --config \
 array_width=100,\
@@ -109,13 +109,13 @@ for FILE in $FILES; do
 done
 
 if [ ! -z $FILES_FORMATTED ]; then
-	echo  "\033[1;34mThese files were formatted, please commit again\033[0m"
+	printf "\033[1;34mThese files were formatted, please commit again\033[0m\n"
 	for FILE in $FILES_FORMATTED; do echo $FILE; done
 	exit 1
 fi
 
 # We can update our eslint config by running `eslint init` again
-echo  "\033[1;34mRunning eslint\033[0m"
+printf "\033[1;34mRunning eslint\033[0m\n"
 FILES_FORMATTED=""
 for FILE in $FILES; do
 	if [ ${FILE##*.} != "ts" ] && [ ${FILE##*.} != "js" ]; then break; fi
@@ -124,15 +124,15 @@ for FILE in $FILES; do
 	if [ "$?" -ne 0 ]; then
 		$ESLINT --fix $FILE > /dev/null 2>&1
 		FILES_FORMATTED="${FILES_FORMATTED}${FILE}\n"
-    fi
+	fi
 done
 
 if [ ! -z $FILES_FORMATTED ]; then
-	echo  "\033[1;34mThese files were formatted, please commit again\033[0m"
+	printf "\033[1;34mThese files were formatted, please commit again\033[0m\n"
 	for FILE in $FILES_FORMATTED; do echo $FILE; done
 	exit 1
 fi
 
 # If it hasn't already failed, allow for commit
-echo  "\033[1;34mPassed linters, proceeding to commit\033[0m"
+printf "\033[1;34mPassed linters, proceeding to commit\033[0m\n"
 exit 0
