Updates pre-commit
it has become cool (works on even more minimal setups)

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,51 +1,65 @@
 #!/bin/sh
-# TODO: Make it use a typescript linter too
 echo -e "\e[1;34mRunning pre-commit hook\e[0m"
 
 FILES=$(git diff --cached --name-only --diff-filter=ACM | \
 	grep -e "\.rs$\|\.[tj]s$")
 
 # If there is nothing to check, no need to format
-if [[ $FILES == "" ]]; then exit 0; fi
+if [ -z $FILES ]; then exit 0; fi
 
 # Check that rustup is installed
-rustup --version &> /dev/null
-if [[ "$?" != 0 ]]; then
+rustup --version > /dev/null 2>&1
+if [ "$?" -ne 0 ]; then
 	echo -e "\e[1;31mCan't find rustup, please install it/add it to path\e[0m"
 	exit 1
 fi
 
+# Check that nightly is installed (for rustfmt)
+if [ -z "$(rustup toolchain list | grep nightly)" ]; then
+	echo -e "rustup nightly not found, attempting to install"
+	echo -e "Running \"\e[0;34mrustup toolchain install nightly\e[0m\""
+    rustup toolchain install nightly
+    
+	# If it couldn't install, fail
+    if [ "$?" -ne 9 ]; then exit 1; fi
+fi
+
 # Check that rustfmt is installed. If not, try to install
-rustfmt --version &> /dev/null
-if [[ "$?" != 0 ]]; then
+rustfmt --version > /dev/null 2>&1
+if [ "$?" -ne 0 ]; then
 	echo -e "rustfmt not found, attempting to install"
 	echo -e "Running \"\e[0;34mrustup component add rustfmt\e[0m\""
-	rustup component add rustfmt
+	rustup component add rustfmt --toolchain nightly
 
-	# If it couldn't install, fail
-	if [[ "$?" == 1 ]]; then exit 1; fi
+	if [ "$?" -ne 0 ]; then exit 1; fi
 fi
 
 # Check that clippy is installed. If not, try to install
-clippy-driver --version &> /dev/null
-if [[ "$?" != 0 ]]; then
+clippy-driver --version > /dev/null 2>&1
+if [ "$?" -ne 0 ]; then
 	echo -e "clippy not found, attempting to install"
 	echo -e "Running \"\e[0;34mrustup component add clippy\e[0m\""
 	rustup component add clippy 
 
-	# If it couldn't install, fail
-	if [[ "$?" == 1 ]]; then exit 1; fi
+	if [ "$?" -ne 0 ]; then exit 1; fi
 fi
 
 # Check that npm is installed
-npm --version &> /dev/null
-if [[ "$?" != 0 ]]; then
+npm --version > /dev/null 2>&1
+if [ "$?" -ne 0 ]; then
 	echo -e "\e[1;31mCan't find nodejs, please install it/add it to path\e[0m"
 	exit 1
 fi
 
 # Check that eslint is installed. If not, try to install
-if [[ ! -f ./node_modules/.bin/eslint ]]; then npm install; fi
+if [ ! -f ./node_modules/.bin/eslint ]; then 
+	echo -e "eslint not found, attempting to install"
+	echo -e "Running \"\e[0;34mrnpm install\e[0m\""
+	npm install
+
+	if [ "$?" -ne 0 ]; then exit 1; fi
+fi
+
 ESLINT="./node_modules/.bin/eslint"
 	
 
@@ -59,10 +73,10 @@ cargo clippy -- -A \
 	clippy::blocks-in-if-conditions \
 	-D warnings
 
-if [[ "$?" != 0 ]]; then exit 1; fi
+if [ "$?" -ne 0 ]; then exit 1; fi
 
 echo -e "\e[1;34mRunning rustfmt\e[0m"
-FILES_FORMATTED=()
+FILES_FORMATTED=""
 RUSTFMT_OPTIONS="--unstable-features --config \
 array_width=100,\
 blank_lines_upper_bound=2,\
@@ -83,31 +97,41 @@ trailing_comma=Always,\
 wrap_comments=true"
 
 for FILE in $FILES; do
-	if [[ ${FILE: -3} != ".rs" ]]; then break; fi
+	if [ ${FILE##*.} != "rs" ]; then break; fi
 
-	rustfmt +nightly $FILE --check $RUSTFMT_OPTIONS &> /dev/null
+	rustfmt +nightly $FILE --check $RUSTFMT_OPTIONS
 
-	if [[ "$?" != 0 ]]; then 
-		rustfmt +nightly $FILE $RUSTFMT_OPTIONS
-		FILES_FORMATTED+=($FILE); 
+	if [ "$?" -ne 0 ]; then 
+		rustfmt +nightly $FILE $RUSTFMT_OPTIONS > /dev/null 2>&1
+		FILES_FORMATTED="${FILES_FORMATTED}${FILE}\n"
 	fi
 
 done
 
-if [[ ${#FILES_FORMATTED[@]} != 0 ]]; then
+if [ ! -z $FILES_FORMATTED ]; then
 	echo -e "\e[1;34mThese files were formatted, please commit again\e[0m"
-	for FILE in ${FILES_FORMATTED[@]}; do echo $FILE; done
+	for FILE in $FILES_FORMATTED; do echo $FILE; done
 	exit 1
 fi
 
 # We can update our eslint config by running `eslint init` again
 echo -e "\e[1;34mRunning eslint\e[0m"
+FILES_FORMATTED=""
 for FILE in $FILES; do
-	if [[ ${FILE: -3} != ".ts" ]] && [[ ${FILE: -3} != ".js" ]]; then break; fi
+	if [ ${FILE##*.} != "ts" ] && [ ${FILE##*.} != "js" ]; then break; fi
 	$ESLINT $FILE
 
-	# TODO: reject if it doesn't like it
+	if [ "$?" -ne 0 ]; then
+		$ESLINT --fix $FILE > /dev/null 2>&1
+		FILES_FORMATTED="${FILES_FORMATTED}${FILE}\n"
+    fi
 done
+
+if [ ! -z $FILES_FORMATTED ]; then
+	echo -e "\e[1;34mThese files were formatted, please commit again\e[0m"
+	for FILE in $FILES_FORMATTED; do echo $FILE; done
+	exit 1
+fi
 
 # If it hasn't already failed, allow for commit
 echo -e "\e[1;34mPassed linters, proceeding to commit\e[0m"
